Repository AztecProtocol/barretenberg, pull requests merged in 2023-02, with the labels that each got.

#98 Fixed stdlib ecdsa issue and added benchmarking to the test
  cpp/src/aztec/stdlib/encryption/ecdsa/ecdsa.test.cpp
  cpp/src/aztec/stdlib/primitives/bigfield/bigfield_impl.hpp
Labels: bug

#94 Commit to Wires Using Lagrange SRS
  cpp/bootstrap.sh
  cpp/scripts/run_tests
  cpp/src/aztec/benchmark/pippenger_bench/main.cpp
  cpp/src/aztec/ecc/curves/bn254/scalar_multiplication/pippenger.cpp
  cpp/src/aztec/ecc/curves/bn254/scalar_multiplication/pippenger.hpp
  cpp/src/aztec/honk/pcs/commitment_key.hpp
  cpp/src/aztec/honk/proof_system/verifier.test.cpp
  cpp/src/aztec/join_split_example/proofs/join_split/c_bind.cpp
  cpp/src/aztec/lagrange_base_gen/lagrange_base_processor.cpp
  cpp/src/aztec/numeric/bitop/pow.hpp
  cpp/src/aztec/plonk/composer/composer_base.cpp
  cpp/src/aztec/plonk/proof_system/prover/c_bind.cpp
  cpp/src/aztec/plonk/proof_system/prover/c_bind_unrolled.cpp
  cpp/src/aztec/plonk/proof_system/prover/prover.cpp
  cpp/src/aztec/plonk/proof_system/prover/prover.hpp
  cpp/src/aztec/plonk/proof_system/verifier/verifier.test.cpp
  cpp/src/aztec/proof_system/proving_key/proving_key.hpp
  cpp/src/aztec/proof_system/work_queue/work_queue.cpp
  cpp/src/aztec/proof_system/work_queue/work_queue.hpp
  cpp/src/aztec/srs/reference_string/file_reference_string.cpp
  cpp/src/aztec/srs/reference_string/file_reference_string.hpp
  cpp/src/aztec/srs/reference_string/pippenger_reference_string.hpp
  cpp/src/aztec/srs/reference_string/reference_string.hpp
Labels: optimization

#154 [CPM] add missing dependencies to libbarretenberg.a
  cpp/src/aztec/CMakeLists.txt
Labels: aztec3, copy-to-master

#119 Make Sumcheck Relations uniform + Efficient Pow
  cpp/src/aztec/honk/composer/standard_honk_composer.test.cpp
  cpp/src/aztec/honk/proof_system/prover.cpp
  cpp/src/aztec/honk/proof_system/verifier.cpp
  cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
  cpp/src/aztec/honk/sumcheck/polynomials/pow.test.cpp
  cpp/src/aztec/honk/sumcheck/relations/arithmetic_relation.hpp
  cpp/src/aztec/honk/sumcheck/relations/grand_product_computation_relation.hpp
  cpp/src/aztec/honk/sumcheck/relations/grand_product_initialization_relation.hpp
  cpp/src/aztec/honk/sumcheck/relations/relation.hpp
  cpp/src/aztec/honk/sumcheck/relations/relation.test.cpp
  cpp/src/aztec/honk/sumcheck/sumcheck.hpp
  cpp/src/aztec/honk/sumcheck/sumcheck.test.cpp
  cpp/src/aztec/honk/sumcheck/sumcheck_round.hpp
  cpp/src/aztec/honk/sumcheck/sumcheck_round.test.cpp
  cpp/src/aztec/honk/utils/power_polynomial.hpp
  cpp/src/aztec/proof_system/flavor/flavor.hpp
  cpp/src/aztec/proof_system/types/polynomial_manifest.hpp
Labels: enhancement

#167 add missing to_nt converts
  cpp/src/aztec/stdlib/types/convert.hpp
Labels: aztec3

#169 Increase Pedersen Generator indices and subindices.
  cpp/src/aztec/crypto/generators/generator_data.cpp
  cpp/src/aztec/join_split_example/proofs/join_split/join_split.test.cpp
Labels: aztec3
